site_name: REZONA (ONA)
site_description: REZONA — a harmonic, MEV-resistant blockchain with Oscillation‑Normalized Agreement (ONA).
theme:
  name: material
  features:
    - navigation.instant
    - toc.integrate
  palette:
    scheme: default
extra_css:
  - assets/stylesheets/extra.css

nav:
  - REZONA (ONA): index.md
  - Whitepaper: whitepaper.md
  - Brand & Logo: brand-guide.md
  - Specs:
    - Fair Gateway (Deposits & Withdrawals): specs/fair-gateway.md
    - Exchange Fairness Add-On (FSE + FFB): specs/exchange-fairness-addon.md
      - Specs:
    - Fair Gateway (Deposits & Withdrawals): specs/fair-gateway.md
    - Exchange Fairness Add-On (FSE + FFB): specs/exchange-fairness-addon.md
    - Fee Router (Multi-Asset Fees): specs/fee-router.md
    - Liquidity Architecture: specs/liquidity-architecture.md

  - Components:
    - FFB Badge Chip: components/ffb-badge.md

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
