site_name: REZONA (ONA)
site_description: REZONA — a harmonic, MEV-resistant blockchain.
theme:
  name: material
  features:
    - navigation.instant
    - toc.integrate
nav:
  - Home: index.md
  - Whitepaper: whitepaper.md
  - Brand Guide: brand-guide.md
  - Specs:
    - Exchange Fairness Add-On: specs/exchange-fairness-addon.md
    - Fair Gateway (Deposits & Withdrawals): specs/fair-gateway.md
